# Generated by Django 4.2.4 on 2023-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(default="user-icon.jpg", upload_to="images"),
                ),
                ("student_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("roll_no", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=30)),
                ("enrollment_year", models.PositiveIntegerField()),
                ("completion_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=150)),
                ("gender", models.CharField(max_length=10)),
                ("emergency_contact", models.CharField(max_length=15)),
                ("blood_group", models.CharField(max_length=5)),
                ("medical_conditions", models.TextField()),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes")),
                ("card_issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("id_card_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
