# Generated by Django 4.2.4 on 2023-08-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="card_issue_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="completion_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_year",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="expiry_date",
            field=models.CharField(max_length=20),
        ),
    ]
