# Generated by Django 4.2.4 on 2023-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_student_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, default="user-icon.jpg", upload_to="images"
            ),
        ),
    ]
