# Generated by Django 4.2.5 on 2023-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("college_staff", "College Staff"),
                ],
                default="student",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("computer", "Computer"),
                    ("economics", "Economics"),
                    ("english", "English"),
                    ("mathematics", "Mathematics"),
                    ("chemistry", "Chemistry"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
