# Generated by Django 4.2.5 on 2023-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_student_role_alter_student_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("college_staff", "College Staff"),
                ],
                default="student",
                max_length=15,
                null=True,
            ),
        ),
    ]
