# Generated by Django 4.2.5 on 2023-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_student_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="completion_date",
            new_name="session",
        ),
        migrations.RemoveField(
            model_name="student",
            name="enrollment_year",
        ),
        migrations.RemoveField(
            model_name="student",
            name="medical_conditions",
        ),
        migrations.AddField(
            model_name="student",
            name="student_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fsc 1st year", "Fsc 1st year"),
                    ("fsc 2nd year", "Fsc 2nd year"),
                    ("bachelor", "Bachelor"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
