# Generated by Django 4.2.5 on 2024-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_completion_date_student_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
