# Generated by Django 4.2.5 on 2026-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="card_issue_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
